name: typed_asset
description: '[WIP] The Dart code generator for your assets. - Get rid of all String-based APIs!'
version: 0.0.0
homepage: https://github.com/mono0926/typed_asset
author: Masayuki Ono <mono0926@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
